package l2tp

// https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/l2tp.h

/*
 * Commands.
 * Valid TLVs of each command are:-
 * TUNNEL_CREATE	- CONN_ID, pw_type, netns, ifname, ipinfo, udpinfo, udpcsum
 * TUNNEL_DELETE	- CONN_ID
 * TUNNEL_MODIFY	- CONN_ID, udpcsum
 * TUNNEL_GETSTATS	- CONN_ID, (stats)
 * TUNNEL_GET		- CONN_ID, (...)
 * SESSION_CREATE	- SESSION_ID, PW_TYPE, cookie, peer_cookie, l2spec
 * SESSION_DELETE	- SESSION_ID
 * SESSION_MODIFY	- SESSION_ID
 * SESSION_GET		- SESSION_ID, (...)
 * SESSION_GETSTATS	- SESSION_ID, (stats)
 *
 */

const (
	L2TP_CMD_NOOP = iota
	L2TP_CMD_TUNNEL_CREATE
	L2TP_CMD_TUNNEL_DELETE
	L2TP_CMD_TUNNEL_MODIFY
	L2TP_CMD_TUNNEL_GET
	L2TP_CMD_SESSION_CREATE
	L2TP_CMD_SESSION_DELETE
	L2TP_CMD_SESSION_MODIFY
	L2TP_CMD_SESSION_GET
)

// ATTR types defined for L2TP
const (
	L2TP_ATTR_NONE = iota
	L2TP_ATTR_PW_TYPE
	L2TP_ATTR_ENCAP_TYPE
	L2TP_ATTR_OFFSET
	L2TP_ATTR_DATA_SEQ
	L2TP_ATTR_L2SPEC_TYPE
	L2TP_ATTR_L2SPEC_LEN
	L2TP_ATTR_PROTO_VERSION
	L2TP_ATTR_IFNAME
	L2TP_ATTR_CONN_ID      // tunnel id
	L2TP_ATTR_PEER_CONN_ID // peer tunnel id
	L2TP_ATTR_SESSION_ID
	L2TP_ATTR_PEER_SESSION_ID
	L2TP_ATTR_UDP_CSUM
	L2TP_ATTR_VLAN_ID
	L2TP_ATTR_COOKIE
	L2TP_ATTR_PEER_COOKIE
	L2TP_ATTR_DEBUG
	L2TP_ATTR_RECV_SEQ
	L2TP_ATTR_SEND_SEQ
	L2TP_ATTR_LNS_MODE
	L2TP_ATTR_USING_IPSEC
	L2TP_ATTR_RECV_TIMEOUT
	L2TP_ATTR_FD
	L2TP_ATTR_IP_SADDR
	L2TP_ATTR_IP_DADDR
	L2TP_ATTR_UDP_SPORT
	L2TP_ATTR_UDP_DPORT
	L2TP_ATTR_MTU
	L2TP_ATTR_MRU
	L2TP_ATTR_STATS
	L2TP_ATTR_IP6_SADDR
	L2TP_ATTR_IP6_DADDR
	L2TP_ATTR_UDP_ZERO_CSUM6_TX
	L2TP_ATTR_UDP_ZERO_CSUM6_RX
	L2TP_ATTR_PAD
)

// Nested in L2TP_ATTR_STATS
const (
	L2TP_ATTR_STATS_NONE = iota
	L2TP_ATTR_TX_PACKETS
	L2TP_ATTR_TX_BYTES
	L2TP_ATTR_TX_ERRORS
	L2TP_ATTR_RX_PACKETS
	L2TP_ATTR_RX_BYTES
	L2TP_ATTR_RX_SEQ_DISCARDS
	L2TP_ATTR_RX_OOS_PACKETS
	L2TP_ATTR_RX_ERRORS
	L2TP_ATTR_STATS_PAD
)

const (
	L2TP_PWTYPE_NONE     = 0x0000
	L2TP_PWTYPE_ETH_VLAN = 0x0004
	L2TP_PWTYPE_ETH      = 0x0005
	L2TP_PWTYPE_PPP      = 0x0007
	L2TP_PWTYPE_PPP_AC   = 0x0008
	L2TP_PWTYPE_IP       = 0x000b
)

const (
	L2TP_L2SPECTYPE_NONE = iota
	L2TP_L2SPECTYPE_DEFAULT
)

const (
	L2TP_ENCAPTYPE_UDP = iota
	L2TP_ENCAPTYPE_IP
)

const (
	L2TP_SEQ_NONE = 0
	L2TP_SEQ_IP   = 1
	L2TP_SEQ_ALL  = 2
)

const (
	L2TP_MSG_DEBUG = 1 << iota
	L2TP_MSG_CONTROL
	L2TP_MSG_SEQ
	L2TP_MSG_DATA
)
